name: Validar Nombre de Rama

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  check-name:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar prefijo
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! $BRANCH_NAME =~ ^(feature|hotfix)/ ]]; then
            echo "Error: La rama '$BRANCH_NAME' no es válida."
            echo "Debe empezar obligatoriamente con feature/ o hotfix/"
            exit 1
          fi
          echo "El nombre de la rama es válido."
